name: flutter_test_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.7.0
  get_it: ^8.0.3
  flutter_bloc: ^8.1.6
  collection: ^1.18.0
  hydrated_bloc: ^9.1.5
  equatable: ^2.0.7
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
